blast_input:
  - sequence_file:     ${seq_file}
  - sequence_format:   ${format}
  - thread:            ${cpus}
  - output_directory:  ${output}
clustering_options:
  - in_memory:         1
  - percent_identity:  90
  - fraction_coverage: 0.55
annotation_input:
  - repeat_database:  ${rmlib}
annotation_options:
  - cluster_size:     100
  - blast_evalue:     10
output:
  - run_log_file:       ${run_log}
  - cluster_log_file:   ${cluster_log}