"""
@author: Jetse

"""
import json, os, sys
 
with open("config.json") as f:
    CONFIG = json.load(f)

# Variant calling:
include: os.path.dirname(sys.argv[2])+"/../../rules/mappers/Bowtie.rules"
include: os.path.dirname(sys.argv[2])+"/../../rules/mappers/BamProcessing.rules"
 
include: os.path.dirname(sys.argv[2])+"/../../rules/variantCalling/SnpCallers.rules"

rule all:
    input: "variantCalling/samtoolsMpileupSnps.vcf"