#!/bin/bash

WORKFLOW_PATH=$1
shift
REST=$@

echo "WORKFLOW PATH       : ${WORKFLOW_PATH}"
echo "REMAINING PARAMETERS: ${REST}"
echo

source activate snakemake && export PYTHONPATH=$PYTHONPATH:/home/snakemake/ && snakemake --directory /home/snakemake/SnakeMakeVlpb/src/workflows/${WORKFLOW_PATH}/ --snakefile /home/snakemake/SnakeMakeVlbp/src/workflows/${WORKFLOW_PATH}/Snakefile ${REST}
