"""

"""

import json, os, inspect

### Get lib configuration
from SnakeMakeVlpb import VLPB_LIB_PATH
 
with open("config.json") as f:
    CONFIG = json.load(f)

## Create a symlink so the data is perfectly fit for all rules. All reads contain the name of their library. 
## All forward reads are {library name}_1.fastq and all reversed reads are {library name}_2.fastq
for sample in CONFIG["libraries"]:
    for i in range(len(CONFIG["libraries"][sample]["reads"])):
        try:
            if os.path.exists("preprocessing") == False:
                os.mkdir("preprocessing")
            os.symlink(CONFIG["libraries"][sample]["reads"][i], "preprocessing/"+ sample +"_" + str(i+1) + ".fastq")
        except FileExistsError:
            pass

ruleDir = VLPB_LIB_PATH + "rules/"

#Preprocessing     
include: ruleDir + "fastqProcessors/Trimmomatic.rules"
include: ruleDir + "fastqProcessors/Quake.rules"
include: ruleDir + "fastqProcessors/FastqMcf.rules"
include: ruleDir + "fastqProcessors/ContaminationFiltering.rules"

#Assembly
include: ruleDir + "assemblers/Wgs.rules"

rule all:
    input: "assembly/wgs.contigs.fasta"