"""

"""
import json, os, inspect

# Get lib configuration
# Set PYTHONPATH before running Snakemake :
# export PYTHONPATH=$PYTHONPATH:/home/haars001/scratch/projects/VLPB/
from SnakeMakeVlpb import VLPB_LIB_PATH

ruleDir = VLPB_LIB_PATH + "rules/"

# Load configuration
with open("config.json") as f:
    CONFIG = json.load(f)

include: ruleDir + "/assemblers/Allpaths.rules"

rule all:
    input: "assembly/allpaths.contigs.fasta"
